name: test
on: push
jobs:
   test:
     runs-on: ubuntu-22.04
     container: ryuichiueda/ubuntu22.04-ros2:latest #前ページのコンテナを使うという宣言
     steps:
       - uses: actions/checkout@v2    #コンテナのカレントディレクトリにリポジトリを配置
       - name: build and test
         run: |
           rsync -av ./ /root/Ros/src/mypkg/
           cd /root/Ros
           rosdep update                                            #14行目のために必要
           rosdep install -i --from-path src --rosdistro humble -y  #不要だけど念のため
           bash -xv ./src/mypkg/test/test.bash /root
